### ISSUE TITLE
Maze Map Generation Not Working

### ISSUE THREAD

**Issue by chareon** [Refactorio/RedMew#290]
Uncommenting either maze shape (require "map_gen.shape.maze") or (require "map_gen.shape.infinite_mazes") from map_layout.lua does not result in any change to map generation.

**Comment by mheguy** [comment]
@Jayefuu any chance you could look at this when you have some time?

**Comment by Jayefuu** [comment]
I'll have a go. Can't promise anything though.

**Comment by TLCPlusPlus** [comment]
Thought this was relevant enough to post in here, I would like to toss in that uncommenting "shape = b.rectangular_spiral" does nothing to my worlds.

**Comment by Valansch** [comment]
@VirusRenamon 
```
shape = b.rectangular_spiral(128)
```
This works for me.

**Comment by TLCPlusPlus** [comment]
@Valansch 

`shape = b.rectangular_spiral(90)`

That is what I use. Am I missing something? I know its working because I get the GUI popup on a new map, but don't see any map differences.

This is the first time I am using it so I may be missing something?
My goal is to try to get a spiral map going.

EDIT: Never mind, I was impatient and apparently I had to wait about 10~ seconds for the changes to happen.

**Comment by Valansch** [comment]
fixed in #631
