### ISSUE TITLE
Implement Arena

### ISSUE THREAD

**Issue by Valansch** [Refactorio/RedMew#80]
- Implement command that spawns a big arena. (Admins) 
- Implement command that makes it possible to join the arena
  - Players in the arena are on opposing forces (FFA)
  - Can still chat
  - Get gear
  - Either set their spawn to the arena or make them leave the arena when they die
- Implement /leavearena

**Comment by mheguy** [comment]
I'm not sure this interests me as a feature, but I'm interested thinking the implementation through:
/arena-create creates an `arena` surface. Plenty of rocks, trees, hills, ,water and in permanent night. An indestructible perimeter wall surrounds the arena.
/arena-join creates a new force (arena#), assigns the player to that force, creates a GUI to toggle their flashlight, gives them basic items, 

----

I actually stopped here because I had a thought: there's a maximum number of forces we can create currently (61). This makes FFA unviable as near as I can tell.

**Comment by Valansch** [comment]
Why does 61 forces make FFA unviable? Just cap the number of players inside a FFA arena to 50. It's not like this will be a huge problem. Even if we get say 100 players we could pair them up :)

**Comment by mheguy** [comment]
Moved to Val's project.
